version: '3.5'

## Creates a full stack development environment containing:
##  Three HTML servers for static content (one for each app)
##  Three PHP servers for the backends (one for each app)
##  An online IDE
##  A reverse proxy to aggregate all the web resources under one path

## List all the "services" - each "service" is a docker container
##
## Note that each service has a "networks" definition; this allows us to define one or more
## virtual networks. Containers on the same network can see each other.
services:

  ##############################################################################
  ## Static web servers
  ##############################################################################
  html01:
    image: hal313/html-01:latest
    container_name: html-01
    networks:
      - full_stack
    ## volumes:
    ##   - "${PROJECT_ROOT}/html-01/app:/usr/local/apache2/htdocs"

  html02:
    image: hal313/html-02:latest
    container_name: html-02
    networks:
      - full_stack
    ## volumes:
    ##   - "${PROJECT_ROOT}/html-02/app:/usr/local/apache2/htdocs"

  html03:
    image: hal313/html-03:latest
    container_name: html-03
    networks:
      - full_stack
    ## volumes:
    ##   - "${PROJECT_ROOT}/html-03/app:/usr/local/apache2/htdocs"

  ##############################################################################
  ## Backend PHP servers
  ##############################################################################
  remote01:
    image: hal313/remote-01:latest
    container_name: api-echo-remote-01
    networks:
      - full_stack
    ## volumes:
    ##   - "${PROJECT_ROOT}/remote-01/app:/var/www/html"

  remote02:
    image: hal313/remote-02:latest
    container_name: api-reverse-remote-02
    networks:
      - full_stack
    ## volumes:
    ##   - "${PROJECT_ROOT}/remote-02/app:/var/www/html"

  remote03:
    image: hal313/remote-03:latest
    container_name: api-uppercase-remote-03
    networks:
      - full_stack
    ## volumes:
    ##   - "${PROJECT_ROOT}/remote-03/app:/var/www/html"


  ## A web-based IDE (Visual Studio Code)
  ide:
    image: codercom/code-server:1.621
    container_name: ide
    command: --allow-http --no-auth
    networks:
      - full_stack
    volumes:
      ## - "${PROJECT_ROOT}/html-01/app:/home/coder/project/html-01"
      ## - "${PROJECT_ROOT}/html-02/app:/home/coder/project/html-02"
      ## - "${PROJECT_ROOT}/remote-02/app:/home/coder/project/remote-02"
      ## TODO: Uncomment this line to persist VS Code settings (such as extensions)
      ## - "${VSCODE_SETTINGS_DIR}:/home/coder/.local"


  ## The reverse proxy
  ##
  ## http://localhost:10080
  proxy:
  proxy:
    image: hal313/reverse-proxy:latest
    container_name: reverse-proxy
    networks:
      - full_stack
    ports:
      - 10080:80


## A list of the virtual networks to use
networks:
  ## All the services reside on the same network, 'fullstack'
  full_stack:
    name: full_stack
